"""LangGraph investigation graph (Phase 4).

State machine (see AGENTS.md):

    START -> TRIAGE -> INVESTIGATE -> RETRIEVE -> ASSESS -> XAI
          -> CHECK_UNCERTAINTY -> [REQUEST_EVIDENCE -> REINVESTIGATE]
          -> GENERATE_ACTIONS -> COUNTERFACTUAL -> POLICY -> RECOMMEND -> END

Design rules enforced here:
  * graph evidence is authoritative — every number the nodes report is read
    from a live TigerGraph query or from the deterministic builder, never
    generated by the LLM;
  * every node appends a real trace entry (tool, HTTP status, latency);
  * the only branch in the graph is evidence sufficiency, and the
    request-evidence loop is bounded to one round by construction.
"""
from __future__ import annotations

import os
import sys
import io
import json
import time
from typing import Any, Dict, List

if not getattr(sys.stdout, "_hhg_wrapped", False):
    _w = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    _w._hhg_wrapped = True
    sys.stdout = _w

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from langgraph.graph import StateGraph, START, END  # noqa: E402

from agent.state import InvestigationState, EMPTY_STATE, trace_from, timings_from  # noqa: E402
from agent.nodes.core import (  # noqa: E402
    triage,
    graph_evidence,
    relationships,
    risk_score,
    xai,
    check_uncertainty,
    request_evidence,
    reinvestigate,
    generate_actions,
    counterfactual,
    policy_gate,
    recommend,
)


def _route_after_triage(state: InvestigationState) -> str:
    """UNKNOWN_CASE is a first-class outcome: no investigation without a case."""
    return "END" if state.get("status") == "UNKNOWN_CASE" else "investigate"


def _route_after_uncertainty(state: InvestigationState) -> str:
    """INSUFFICIENT evidence is allowed, but the loop runs at most once."""
    if state.get("uncertainty") == "INSUFFICIENT" and int(state.get("round", 0)) < 1:
        return "request_evidence"
    return "generate_actions"


def build_graph():
    g = StateGraph(InvestigationState)

    g.add_node("triage", triage)
    g.add_node("investigate", graph_evidence)
    g.add_node("retrieve", relationships)
    g.add_node("assess", risk_score)
    g.add_node("xai", xai)
    g.add_node("check_uncertainty", check_uncertainty)
    g.add_node("request_evidence", request_evidence)
    g.add_node("reinvestigate", reinvestigate)
    g.add_node("generate_actions", generate_actions)
    g.add_node("counterfactual", counterfactual)
    g.add_node("policy", policy_gate)
    g.add_node("recommend", recommend)

    g.add_edge(START, "triage")
    g.add_conditional_edges("triage", _route_after_triage, {"END": END, "investigate": "investigate"})
    g.add_edge("investigate", "retrieve")
    g.add_edge("retrieve", "assess")
    g.add_edge("assess", "xai")
    g.add_edge("xai", "check_uncertainty")
    g.add_conditional_edges(
        "check_uncertainty",
        _route_after_uncertainty,
        {"request_evidence": "request_evidence", "generate_actions": "generate_actions"},
    )
    g.add_edge("request_evidence", "reinvestigate")
    g.add_edge("reinvestigate", "generate_actions")
    g.add_edge("generate_actions", "counterfactual")
    g.add_edge("counterfactual", "policy")
    g.add_edge("policy", "recommend")
    g.add_edge("recommend", END)

    return g.compile()


_APP = None


def app():
    global _APP
    if _APP is None:
        _APP = build_graph()
    return _APP


def run_case(case_id: str) -> Dict[str, Any]:
    """Run one case end to end and return the final state (JSON-safe).

    Never raises for a bad case id: an unknown case returns status
    UNKNOWN_CASE with an empty trace, which is itself an honest result.
    """
    t0 = time.time()
    state: InvestigationState = EMPTY_STATE(case_id)
    try:
        final = app().invoke(state)
    except Exception as exc:  # pragma: no cover - defensive
        final = dict(state)
        final["status"] = "ERROR"
        final["errors"] = list(final.get("errors") or []) + [
            "%s: %s" % (type(exc).__name__, str(exc)[:300])
        ]
    final["latency_s"] = round(time.time() - t0, 3)
    return _jsonable(final)


def _jsonable(o: Any) -> Any:
    """numpy / pandas scalars -> plain python, then JSON dump."""
    if isinstance(o, dict):
        return {str(k): _jsonable(v) for k, v in o.items()}
    if isinstance(o, (list, tuple)):
        return [_jsonable(v) for v in o]
    if isinstance(o, (str, bool, type(None))):
        return o
    if isinstance(o, (int,)):
        return int(o)
    if isinstance(o, float):
        return float(o)
    for attr in ("item", "tolist"):          # numpy scalar / array
        f = getattr(o, attr, None)
        if callable(f) and type(o).__module__.startswith("numpy"):
            return _jsonable(f())
    try:
        return float(o)
    except Exception:
        return str(o)


if __name__ == "__main__":
    cid = sys.argv[1] if len(sys.argv) > 1 else "HHG-001"
    out = run_case(cid)
    print(json.dumps({k: out.get(k) for k in
                      ("case_id", "status", "uncertainty", "tool_calls",
                       "tokens", "latency_s", "errors")}, indent=2))
    d = out.get("decision") or {}
    print(json.dumps({"verdict": d.get("verdict"), "p0": d.get("p0"),
                      "p1": d.get("p1"), "next_best_action":
                      (out.get("policy") or {}).get("action")}, indent=2))
